name: Zircon3D Proxy
description: "This add-on allows accessing Zircon3D system from Home Assistant"
version: "1.0.9"
slug: zircon3d_ha_proxy
image: lichr/zircon3d-ha-proxy-{arch}
panel_title: Zircon3D
panel_icon: mdi:floor-plan
init: false
ingress: true
ingress_port: 11200
homeassistant_api: true
ports:
  11200/tcp: 11200
arch:
  - amd64
options:
  zircon_access_token: null
  group: null
  project: null
schema:
  zircon_access_token: str
  group: "match(^[a-zA-Z0-9]+$)"
  project: "match(^[a-zA-Z0-9]+$)"
