name: Zircon3D Proxy
description: "This add-on allows accessing Zircon3D system from Home Assistant"
version: "1.0.3"
slug: zircon3d_proxy
panel_title: Zircon3D
panel_icon: mdi:floor-plan
init: false
ingress: true
ingress_port: 3100
ports:
  3100/tcp: 3100
arch:
  - amd64
options:
  email: null
  password: null
  group: null
  project: null
schema:
  email: email
  password: password
  group: "match(^[a-zA-Z0-9]+$)"
  project: "match(^[a-zA-Z0-9]+$)"
image: lichr/zircon-ha-proxy-{arch}
